### ISSUE TITLE
How to clear the cache?

### ISSUE THREAD

**Issue by gb5256** [noam148/yii2-image-resize#5]
HI.
First: thanks for this extension, I am using it massively.

I have right now two questions about clearing the cache:
1. How to clear the cache completely?
2. How to clear the cache just for one image?

The second one is for the case if an image is re-uploaded and thus has the same name, but might be different in content. In that case it would be cool if I could manually trigger a deletion of the old cached files, something like this:
\Yii::$app->imageresize->clearCache($filename);

I do see a function "clearCache" in your code, but it is not working. If I call it like
\Yii::$app->imageresize->clearCache();
it throws errors. I suppose it is meant for my Question 1 above, deleting all caches, right?

Any help highly appreciated.
gb5256

**Comment by noam148** [comment]
Hi @gb5256 ,

The method clearCache should remove all files, what is the error you get?

At the moment i'm very busy, maybe you can make a pull request with the possibility to remove single cached files?

Regards,
Noam
